version: 0.1

## Use newman to run a postman collection.  The env.json file is created magically by the pipeline with BASE_URL defined

phases:
  install:
    commands:
      - npm install newman --global
  build:
    commands:
      - newman run collection.json -e env.json -r html,json,junit,cli

artifacts:
  files:
    - newman/*

