environments:
- name: acceptance
  loadbalancer:
    hostedzone: aws.godfrey.io
  cluster:
    desiredCapacity: 1
    sshAllow: 10.0.0.0/16
- name: production
  loadbalancer:
    hostedzone: aws.godfrey.io
  cluster:
    desiredCapacity: 1
    sshAllow: 10.0.0.0/16
service:
  name: banana-service
  port: 8080
  pathPatterns:
  - /bananas/*
  pipeline:
    source:
      provider: GitHub
      repo: warnergodfrey/banana-service
    build:
      image: aws/codebuild/java:openjdk-8
templates:
  mu-environment-acceptance:
    Resources:
      ScheduledActionUp:
        Type: "AWS::AutoScaling::ScheduledAction"
        Properties:
          AutoScalingGroupName:
            Ref: EcsAutoScalingGroup
          DesiredCapacity: 1
          MinSize: 1
          Recurrence: "0 23 * * *"
      ScheduledActionDown:
        Type: "AWS::AutoScaling::ScheduledAction"
        Properties:
          AutoScalingGroupName:
            Ref: EcsAutoScalingGroup
          DesiredCapacity: 0
          MinSize: 0
          Recurrence: "0 7 * * *"
